plugins {
    alias(libs.plugins.kotlin.jvm)
}

group = 'io.finapi'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // use version catalog aliases from gradle/libs.versions.toml
    testImplementation libs.kotlin.test
}

kotlin {
    jvmToolchain(21)
}

test {
    useJUnitPlatform()
}
