import dev.detekt.gradle.Detekt
import dev.detekt.gradle.DetektCreateBaselineTask
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id "signing"
    id "maven-publish"
    alias(libs.plugins.version.catalog.update)
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.jetbrains.compose) apply false
    alias(libs.plugins.jetbrains.compose.kotlin.plugin) apply false
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.jreleaser) apply false
    alias(libs.plugins.kotlin.dokka) apply false
}

apply from: "${rootDir}/config/gradle/wrapper.gradle"
apply from: "${rootDir}/config/gradle/version_updates.gradle"

subprojects {
    // export of classes for subscripts
    ext.KotlinCompile = KotlinCompile
    ext.JvmTarget = JvmTarget
    ext.Detekt = Detekt
    ext.DetektCreateBaselineTask = DetektCreateBaselineTask

    apply plugin: "maven-publish"
    apply plugin: "org.jetbrains.dokka"
    apply plugin: "org.jreleaser"
    apply from: "${rootDir}/config/gradle/publishing.gradle"

    apply from: "${rootDir}/config/gradle/java.gradle"
    apply from: "${rootDir}/config/gradle/dokka.gradle"
    apply from: "${rootDir}/config/gradle/testing.gradle"
    apply from: "${rootDir}/config/gradle/static_analysis.gradle"
}
