plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.3.21'
}

group = 'io.finapi'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // use version catalog aliases from gradle/libs.versions.toml
    testImplementation libs.kotlinTest
    implementation libs.jacksonModuleKotlin
    implementation libs.jacksonDataformatYaml
}

kotlin {
    jvmToolchain(21)
}

test {
    useJUnitPlatform()
}
