[versions]
kotlin = "2.3.21"
# Jackson 3 series - prefer the latest compatible 3.x release. You can update this to a newer patch version if available.
jackson2 = "2.22"
jackson3 = "3.2.0"

[libraries]
# Kotlin test libraries
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

# --- Jackson
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson2" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson3" }
jackson-jaxb = { module = "tools.jackson.module:jackson-module-jaxb-annotations", version.ref = "jackson3" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson3" }
jackson-module-blackbird = { module = "tools.jackson.module:jackson-module-blackbird", version.ref = "jackson3" }
jackson-dataformmat-yaml = { module = "tools.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson3" }

[bundles]
jackson = [
    "jackson-annotations",
    "jackson-databind",
    "jackson-dataformmat-yaml",
    "jackson-jaxb",
    "jackson-module-blackbird",
    "jackson-module-kotlin",
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version = "1.11.1" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose-kotlin-plugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "dev.detekt", version = "2.0.0-alpha.4" }
