plugins {
    alias(libs.plugins.kotlin.jvm)
}

group = 'io.finapi.ruleengine'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.bundles.jackson
    testImplementation libs.kotlin.test
}

kotlin {
    jvmToolchain(21)
}

tasks.withType(Test) {
    useJUnitPlatform()
}

