plugins {
    alias(libs.plugins.jetbrains.compose)
    alias(libs.plugins.jetbrains.compose.kotlin.plugin)
    alias(libs.plugins.kotlin.multiplatform)
}

kotlin {
    jvm()
    js(IR) {
        browser()
        binaries.executable()
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material)
                implementation(compose.ui)
            }
        }
        jvmMain {
            dependencies {
                implementation(project(":ruleengine-core"))
                implementation(compose.desktop.currentOs)
            }
        }
        jsMain {
            dependencies {
                // keep JS main independent from core
            }
        }
        jvmTest {
            dependencies {
                implementation(project(":ruleengine-core"))
                runtimeOnly(project(":ruleengine-core"))
                implementation(kotlin("test"))
            }
        }
    }
}

compose.desktop {
    application {
        mainClass = 'ui.DesktopMainKt'
    }
}





