# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 25
      uses: actions/setup-java@v6
      with:
        java-version: 25
        distribution: 'liberica'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Execute tests
      run: ./gradlew test allTests --continue

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v6
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/**/TEST-*.xml'
        detailed_summary: true
        truncate_stack_traces: false

    - name: Upload HTML test reports
      if: success() || failure()
      uses: actions/upload-artifact@v7
      with:
        name: test-reports-html
        path: '**/build/reports/tests/**'
        if-no-files-found: ignore
        retention-days: 7

#    - name: Sonarqube
#      run: ./gradlew sonar
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
